### ISSUE TITLE
해야될 일

### ISSUE THREAD

**Issue by dikum98** [dikum98/HanJoWatch#1]
- [x] HTML Markup 작성
- [x] CSS Style 작성
- [x] JavaScript 기능 구현

**Comment by pereng11** [comment]
HTML Markup 작성하겠습니다

**Comment by pereng11** [comment]
한님 마크업 하시면 제가 CSS 미리 만들어보겠습니다!
클래스명만 먼저 알려주세욥

**Comment by pereng11** [comment]
CSS는 HTML 기다려야 할 수 있을 것 같고 JS는 동시에 진행할 수 있을 것 같은데,
한님 고르시면 제가 남는 거 하겠습니다!

**Comment by dikum98** [comment]
html 하실래요?

**Comment by pereng11** [comment]
좋습니다!
