### ISSUE TITLE
컨벤션

### ISSUE THREAD

**Issue by dikum98** [dikum98/HanJoWatch#3]
커밋 컨벤션은 아래와 같습니다.

prefix | 상황 | 예시
-- | -- | --
feat | 기능 개발, 로직의 변경 | feat: A 기능 개발
refactor | 로직을 바꾸지 않는 코드 상의 변경 | refactor: A 기능 코드 단순화
docs | 코드가 아닌 문서의 변경 | docs: README 변경
fix | 오류 수정, 의도치 않은 동작을 고침 | fix: B 버그 수정
chore | 위의 항목에 해당하지 않는 내용 | chore: prettier 설정 변경

클래스 컨벤션
- 케밥 케이스

**Comment by pereng11** [comment]
확인했습니다!
